services:
    smallstep:
        build: ./ca
        ports: 
            - "9000:9000"
        environment:
            - DOCKER_STEPCA_INIT_NAME=Smallstep
            - DOCKER_STEPCA_INIT_ADDRESS=:9000
            # - STEP_CA_URL=https://smallstep:9000
            - DOCKER_STEPCA_INIT_DNS_NAMES=localhost,smallstep
            - DOCKER_STEPCA_INIT_REMOTE_MANAGEMENT=true
            - DOCKER_STEPCA_INIT_PASSWORD_FILE=/run/secrets/password
            - STEP_PASSWORD_FILE=/run/secrets/password
            - STEP_ADMIN_SUBJECT=step
            - STEP_PROVISIONER=admin
        networks:
            - intranet
        volumes:
            - step:/home/step:rw
        secrets: [ password ]
    fingerprint:
        build: ./fingerprint
        environment:
            - ROOT_CA_FINGERPRINT_PATH=/var/local/step/fingerprint/fingerprint
        # networks:
        #     - intranet
        volumes:
            - fingerprint:/var/local/step/fingerprint:rw
            - step:/home/step:ro
    admin_renewer:
        build: ./oidc-mock-renewer
        networks:
            - intranet
        secrets:
            - password
        environment:
            - CLIENT_CERTS_DIR=/var/local/step/certs
            - STEP_CA_URL=https://smallstep:9000
            - ROOT_CA_FINGERPRINT_PATH=/var/local/step/fingerprint/fingerprint
            - STEPPATH=/home/step
            - STEP_ADMIN_SUBJECT=step
            - STEP_PROVISIONER=admin
            # - STEP=/home/step
            - COMMON_NAME=step
            - STEP_PASSWORD_FILE=/run/secrets/password
        depends_on:
            - smallstep
        volumes:
            - admin_certificates:/var/local/step/certs:rw
            - fingerprint:/var/local/step/fingerprint:rw
            # - step:/home/step:ro
    oidc_mock_renewer:
        build: ./oidc-mock-renewer
        networks:
            - intranet
        secrets:
            - password
        environment:
            - CLIENT_CERTS_DIR=/var/local/step/certs
            - STEP_CA_URL=https://smallstep:9000
            - ROOT_CA_FINGERPRINT_PATH=/var/local/step/fingerprint/fingerprint
            - STEPPATH=/home/step
            - STEP_ADMIN_SUBJECT=step
            - STEP_PROVISIONER=admin
            # - STEP=/home/step
            - COMMON_NAME=mock_oidc
            - STEP_PASSWORD_FILE=/run/secrets/password
        depends_on:
            - smallstep
        volumes:
            - mock_oidc_certificates:/var/local/step/certs:rw
            - fingerprint:/var/local/step/fingerprint:rw
            # - step:/home/step:ro
    mock_oidc:
        build: .
        depends_on: [ oidc_mock_renewer ]
        networks:
            - intranet
        ports:
            - "9999:9000"
        command: /project/bin/oidc-server-mock
        environment:
            - LISTEN_ADDR=mock_oidc:9000
            - CERTFILE=/var/local/step/site.crt
            - KEYFILE=/var/local/step/site.key
            - CAFILE=/var/local/step/root_ca.crt
        volumes:
            - mock_oidc_certificates:/var/local/step:ro
    init_oidc_provider:
        build: ./init_oidc_provider
        depends_on: [ mock_oidc ]
        environment:
            - OIDC_ENDPOINT=https://mock_oidc:9000/oidc/.well-known/openid-configuration
            # - CLIENT_CERTS_DIR=/var/local/step/certs
            - STEP_CA_URL=https://smallstep:9000
            - ROOT_CA_FINGERPRINT_PATH=/var/local/step/fingerprint/fingerprint
            - STEPPATH=/home/step
            - STEP_ADMIN_SUBJECT=step
            - STEP_ADMIN_CREDENTIALS=admin
            # - STEP_PROVISIONER=admin
            # - STEP=/home/step
            - COMMON_NAME=mock_oidc
            - STEP_PASSWORD_FILE=/run/secrets/password
        volumes:
            - fingerprint:/var/local/step/fingerprint:rw
        networks: [ intranet ]
        secrets: [ password ]
    server_renewer:
        build: ./oidc-mock-renewer
        networks:
            - intranet
        secrets:
            - password
        environment:
            - CLIENT_CERTS_DIR=/var/local/step/certs
            - STEP_CA_URL=https://smallstep:9000
            - ROOT_CA_FINGERPRINT_PATH=/var/local/step/fingerprint/fingerprint
            - STEPPATH=/home/step
            - STEP_ADMIN_SUBJECT=step
            - STEP_PROVISIONER=admin
            # - STEP=/home/step
            - COMMON_NAME=server
            - STEP_PASSWORD_FILE=/run/secrets/password
        depends_on:
            - smallstep
        volumes:
            - server_certificates:/var/local/step/certs:rw
            - fingerprint:/var/local/step/fingerprint:rw
    server:
        build: .
        depends_on: [ server_renewer ]
        networks:
            - intranet
        ports: []
            # - "9999:9000"
        command: sh -c 'sleep 10; /project/bin/server'
        environment:
            - LISTEN_ADDR=server:9000
            - JWT_SECRET=hackme
            - CERTFILE=/var/local/step/site.crt
            - KEYFILE=/var/local/step/site.key
            - CAFILE=/var/local/step/root_ca.crt
        volumes:
            - server_certificates:/var/local/step:ro
    client1_renewer:
        build: ./client_renewer
        networks:
            - intranet
        secrets: []
            # - password
        environment:
            - CLIENT_CERTS_DIR=/var/local/step/certs
            - STEP_CA_URL=https://smallstep:9000
            - ROOT_CA_FINGERPRINT_PATH=/var/local/step/fingerprint/fingerprint
            - STEPPATH=/home/step
            - STEP_ADMIN_SUBJECT=step
            - STEP_PROVISIONER=admin
            # - STEP=/home/step
            - COMMON_NAME=server
            - STEP_PASSWORD_FILE=/run/secrets/password
            # - STEP_ADMIN_SUBJECT=step
            # - STEP_PROVISIONER=admin
            # - COMMON_NAME=client1
            # - STEP_PASSWORD_FILE=/run/secrets/password
        depends_on:
            - smallstep
        volumes:
            - client1_certificates:/var/local/step/certs:rw
            # - step:/home/step:ro
            - fingerprint:/var/local/step/fingerprint:rw
    client1:
        build: .
        networks:
            - intranet
        ports: []
            # - "9999:9000"
        command: /project/bin/client
        environment:
            - SERVER_ADDR=server:9000
            - CERTFILE=/var/local/step/site.crt
            - KEYFILE=/var/local/step/site.key
            - CAFILE=/var/local/step/root_ca.crt
        volumes:
            - client1_certificates:/var/local/step:ro
    # client2:
    #     build: .
    #     networks:
    #         - intranet
    #     ports: []
    #         # - "9999:9000"
    #     command: sh -c 'sleep 12; /project/bin/client'
    #     environment:
    #         - SERVER_ADDR=server:9000
    #         - CERTFILE=/var/local/step/site.crt
    #         - KEYFILE=/var/local/step/site.key
    #         - CAFILE=/var/local/step/root_ca.crt
    #     volumes:
    #         - client2_certificates:/var/local/step:rw

networks:
    intranet:
volumes:
    step:
    app:
    mock_oidc_certificates:
    server_certificates:
    client1_certificates:
    client2_certificates:
    admin_certificates:
    fingerprint:
secrets:
    password:
        file: ./password.txt
